# Generated by Django 3.2.8 on 2021-10-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['estado', 'nome']},
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='name',
            new_name='nome',
        ),
    ]
