# Generated by Django 3.2.8 on 2021-10-19 22:33

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211019_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14),
        ),
    ]
