# Generated by Django 3.2.8 on 2021-10-23 04:18

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RG'),
        ),
    ]
