# Generated by Django 3.2.8 on 2021-10-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_endereco_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['state', 'name']},
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='estado',
            new_name='state',
        ),
    ]
