# Generated by Django 3.2.8 on 2021-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211023_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='descricao',
            field=models.CharField(default='RES', max_length=30),
            preserve_default=False,
        ),
    ]
