# Generated by Django 3.2.8 on 2021-11-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_endereco_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PRF', 'Profissional da Saúde'), ('CID', 'Cidadão')], default='CID', max_length=3),
            preserve_default=False,
        ),
    ]
