# Generated by Django 3.2.8 on 2021-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211113_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_inicio_gestacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_gestante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
