# Generated by Django 3.2.8 on 2021-11-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_usuario_posto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceita_email',
            field=models.BooleanField(default=False),
        ),
    ]
