# Generated by Django 3.2.8 on 2021-10-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vacina.posto'),
            preserve_default=False,
        ),
    ]
