# Generated by Django 3.2.8 on 2021-11-10 00:39

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacina', '0002_aplicacao_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacao',
            name='vacina',
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Incluído em:')),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em:')),
                ('ordem', models.IntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('criador', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dose', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:')),
                ('ultimo_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_dose', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacina.vacina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='dose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vacina.dose'),
            preserve_default=False,
        ),
    ]
