# Generated by Django 3.2.8 on 2021-11-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_usuario_tipo'),
        ('vacina', '0003_auto_20211109_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_doses', to='vacina.dose'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='base.usuario'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='vacina.vacina'),
        ),
    ]
