# Generated by Django 3.2.8 on 2021-11-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0006_vacina_qtd_doses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacao',
            options={'ordering': ['-data_aplicacao'], 'verbose_name': 'Aplicação', 'verbose_name_plural': 'Aplicações'},
        ),
        migrations.AlterModelOptions(
            name='doenca',
            options={'ordering': ['nome'], 'verbose_name': 'Doença', 'verbose_name_plural': 'Doenças'},
        ),
        migrations.AlterModelOptions(
            name='fabricantevacina',
            options={'ordering': ['nome'], 'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='vacina',
            options={'ordering': ['nome']},
        ),
    ]
