# Generated by Django 3.2.8 on 2021-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0008_coordenadasposto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='idade_maxima_aplicacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
