# Generated by Django 3.2.8 on 2021-11-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0009_alter_vacina_idade_maxima_aplicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='intervalo_doses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
