# Generated by Django 3.2.8 on 2021-11-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0011_vacina_is_anual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posto',
            options={'ordering': ['nome']},
        ),
    ]
