# Generated by Django 3.2.8 on 2021-11-21 00:26

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacina', '0014_auto_20211120_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='criador',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dose', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por:'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='ordem',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dose',
            name='ultimo_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_dose', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por:'),
        ),
    ]
