# Generated by Django 3.2.8 on 2021-11-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0016_auto_20211120_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='proxima_dose',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Intervalo para a próxima dose (dias)'),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='intervalo_doses',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Intervalo entre as doses (dias)'),
        ),
    ]
